language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"

install:
    - pip install -r requirements/ci.txt --use-mirrors
    
services:
    - redis-server

script: 
    - nosetests tests --with-cov -v
    - flake8 sifr --max-complexity=10
after_success:
    - coveralls
